"""
HTML report renderer — produces a print-ready compliance document.

Usage:
    from render_html import render_dpia, render_rbi_free
    html = render_dpia(report)
    open("dpia.html", "w").write(html)
    # Open in browser → Ctrl+P → Save as PDF
"""

from __future__ import annotations
import json

STATUS_BADGE = {
    "compliant":     ('<span style="background:#D1FAE5;color:#065F46;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">✓ COMPLIANT</span>', "#065F46"),
    "partial":       ('<span style="background:#FEF3C7;color:#92400E;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">◑ PARTIAL</span>', "#92400E"),
    "non_compliant": ('<span style="background:#FEE2E2;color:#991B1B;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">✗ GAP</span>', "#991B1B"),
    "not_assessed":  ('<span style="background:#F3F4F6;color:#6B7280;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:700">– N/A</span>', "#6B7280"),
}

RISK_COLOR = {"low": "#065F46", "medium": "#92400E", "high": "#991B1B"}

_BASE_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Segoe UI', system-ui, sans-serif; color: #111827; background: #fff; font-size: 13px; line-height: 1.6; }
.page { max-width: 900px; margin: 0 auto; padding: 48px 40px; }
.cover { border-bottom: 3px solid #1D4ED8; padding-bottom: 32px; margin-bottom: 40px; }
.cover-badge { font-size: 11px; font-weight: 700; letter-spacing: 0.1em; color: #1D4ED8; text-transform: uppercase; margin-bottom: 10px; }
.cover-title { font-size: 28px; font-weight: 700; color: #111827; margin-bottom: 8px; line-height: 1.2; }
.cover-org { font-size: 18px; color: #374151; margin-bottom: 24px; }
.cover-meta { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 32px; font-size: 12px; color: #6B7280; }
.cover-meta strong { color: #374151; }
.score-banner { background: #EFF6FF; border: 1px solid #BFDBFE; border-radius: 8px; padding: 20px 24px; margin-bottom: 32px; display: flex; align-items: center; gap: 24px; }
.score-num { font-size: 48px; font-weight: 800; color: #1D4ED8; line-height: 1; }
.score-label { font-size: 13px; color: #374151; }
.score-label strong { display: block; font-size: 15px; margin-bottom: 2px; }
.section { margin-bottom: 36px; }
.section-title { font-size: 16px; font-weight: 700; color: #1D4ED8; border-bottom: 1px solid #E5E7EB; padding-bottom: 8px; margin-bottom: 16px; }
.check-item { border: 1px solid #E5E7EB; border-radius: 6px; padding: 12px 16px; margin-bottom: 8px; }
.check-header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 6px; }
.check-id { font-family: monospace; font-size: 11px; color: #9CA3AF; min-width: 40px; padding-top: 1px; }
.check-req { flex: 1; font-weight: 500; font-size: 13px; }
.check-detail { font-size: 12px; color: #6B7280; margin-top: 4px; padding-left: 52px; }
.check-gap { color: #B45309; font-size: 12px; margin-top: 4px; padding-left: 52px; }
.check-rec { color: #1D4ED8; font-size: 12px; margin-top: 4px; padding-left: 52px; font-style: italic; }
.risk-item { border-left: 3px solid #E5E7EB; padding: 10px 14px; margin-bottom: 10px; }
table { width: 100%; border-collapse: collapse; font-size: 12px; margin-bottom: 16px; }
th { background: #F9FAFB; text-align: left; padding: 8px 12px; border: 1px solid #E5E7EB; font-weight: 600; }
td { padding: 8px 12px; border: 1px solid #E5E7EB; vertical-align: top; }
.pillar-score { font-size: 22px; font-weight: 800; }
.summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 24px; }
.stat-box { background: #F9FAFB; border: 1px solid #E5E7EB; border-radius: 6px; padding: 12px 16px; }
.stat-num { font-size: 24px; font-weight: 800; color: #1D4ED8; }
.stat-label { font-size: 11px; color: #6B7280; margin-top: 2px; }
.footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #E5E7EB; font-size: 11px; color: #9CA3AF; display: flex; justify-content: space-between; }
@media print { .page { padding: 24px 32px; } }
"""


def _html_wrap(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>{_BASE_CSS}</style>
</head>
<body>
<div class="page">
{body}
<div class="footer">
  <span>Generated by Svitch Compliance Engine · svitch.ai</span>
  <span>Confidential — For regulatory and internal use only</span>
</div>
</div>
</body>
</html>"""


def _badge(status: str) -> str:
    return STATUS_BADGE.get(status, STATUS_BADGE["not_assessed"])[0]


def _checks_html(checks: list[dict]) -> str:
    out = []
    for c in checks:
        gap_html = f'<div class="check-gap">⚠ Gap: {c["gap"]}</div>' if c.get("gap") else ""
        rec_html = f'<div class="check-rec">→ {c["recommendation"]}</div>' if c.get("recommendation") else ""
        ev_html  = f'<div class="check-detail">Evidence: {c["evidence"]}</div>' if c.get("evidence") else ""
        out.append(f"""
<div class="check-item">
  <div class="check-header">
    <span class="check-id">{c["id"]}</span>
    <span class="check-req">{c["requirement"]}</span>
    {_badge(c["status"])}
  </div>
  {ev_html}{gap_html}{rec_html}
</div>""")
    return "\n".join(out)


def render_dpia(report_dict: dict) -> str:
    meta    = report_dict["meta"]
    summary = report_dict["summary"]
    score   = summary["overall_compliance_score_pct"]
    score_color = "#065F46" if score >= 75 else "#92400E" if score >= 50 else "#991B1B"

    cover = f"""
<div class="cover">
  <div class="cover-badge">Svitch Compliance Engine</div>
  <div class="cover-title">{meta["report_type"]}</div>
  <div class="cover-org">{meta["organisation"]}</div>
  <div class="cover-meta">
    <div><strong>Report ID</strong> {meta["report_id"]}</div>
    <div><strong>Period</strong> {meta["period_start"]} → {meta["period_end"]}</div>
    <div><strong>Prepared by</strong> {meta["prepared_by"]}</div>
    <div><strong>Generated</strong> {meta["generated_at"]}</div>
    <div><strong>Version</strong> {meta["version"]}</div>
    <div><strong>SDF</strong> {"Yes" if summary.get("is_significant_data_fiduciary") else "No"}</div>
  </div>
</div>
<div class="score-banner">
  <div class="score-num" style="color:{score_color}">{score}%</div>
  <div class="score-label">
    <strong>DPDP Compliance Score</strong>
    {summary["pii_events_blocked"]} PII events blocked &nbsp;·&nbsp;
    {summary["human_checkpoints_recorded"]} human checkpoints &nbsp;·&nbsp;
    {summary["total_agent_runs"]} agent runs analysed
  </div>
</div>"""

    sections_html = ""
    for section in report_dict.get("sections", []):
        title = section["title"]
        sections_html += f'<div class="section"><div class="section-title">{section["id"]} — {title}</div>'

        if section["id"] == "S1":
            c = section["content"]
            sections_html += f"""
<div class="summary-grid">
  <div class="stat-box"><div class="stat-num">{c["agent_runs_analysed"]}</div><div class="stat-label">Agent runs analysed</div></div>
  <div class="stat-box"><div class="stat-num">{c["total_pii_events"]}</div><div class="stat-label">PII events blocked</div></div>
  <div class="stat-box"><div class="stat-num">{c["human_checkpoints_used"]}</div><div class="stat-label">Human checkpoints</div></div>
</div>
<table>
<tr><th>PII Category</th><th>DPDP Classification</th></tr>
{"".join(f"<tr><td>{p}</td><td>Personal data requiring consent</td></tr>" for p in c["pii_types_processed"])}
</table>"""

        elif section["id"] == "S5":
            sections_html += f'<p style="margin-bottom:12px">Overall risk level: <strong style="color:{RISK_COLOR.get(section["overall_risk_level"], "#374151")}">{section["overall_risk_level"].upper()}</strong></p>'
            for r in section.get("risks", []):
                border_color = RISK_COLOR.get(r["residual_risk"], "#E5E7EB")
                sections_html += f"""
<div class="risk-item" style="border-color:{border_color}">
  <strong>[{r["id"]}] {r["description"]}</strong><br>
  <span style="font-size:12px;color:#6B7280">
    Likelihood: {r["likelihood"]} · Impact: {r["impact"]} · Residual: <strong style="color:{border_color}">{r["residual_risk"]}</strong>
  </span><br>
  <span style="font-size:12px;margin-top:4px;display:block">✓ {r["mitigation"]}</span>
</div>"""

        elif section["id"] == "S6":
            sections_html += "<table><tr><th>Category</th><th>Measure</th><th>Standard</th><th>Status</th></tr>"
            for m in section.get("measures", []):
                badge = _badge(m["status"])
                sections_html += f"<tr><td><strong>{m['category']}</strong></td><td>{m['measure']}</td><td style='font-size:11px;color:#6B7280'>{m['standard']}</td><td>{badge}</td></tr>"
            sections_html += "</table>"

        elif section["id"] == "S7":
            approved = section.get("approval_recommended", False)
            color = "#065F46" if approved else "#92400E"
            sections_html += f"""
<p><strong>DPO:</strong> {section["dpo_name"]}</p>
<p style="margin-top:12px">{section["recommendation"]}</p>
<p style="margin-top:16px;font-weight:700;color:{color}">
  {"✓ APPROVED FOR DEPLOYMENT" if approved else "◑ CONDITIONAL APPROVAL — ADDRESS GAPS BEFORE PRODUCTION"}
</p>"""

        elif "checks" in section:
            sections_html += _checks_html(section["checks"])

        sections_html += "</div>"

    return _html_wrap(f"DPDP DPIA — {meta['organisation']}", cover + sections_html)


def render_rbi_free(report_dict: dict) -> str:
    meta    = report_dict["meta"]
    summary = report_dict["summary"]
    score   = summary["overall_score_pct"]
    score_color = "#065F46" if score >= 70 else "#92400E" if score >= 45 else "#991B1B"

    cover = f"""
<div class="cover">
  <div class="cover-badge">Svitch Compliance Engine</div>
  <div class="cover-title">RBI FREE Framework Self-Assessment</div>
  <div class="cover-org">{meta["organisation"]}</div>
  <div class="cover-meta">
    <div><strong>Report ID</strong> {meta["report_id"]}</div>
    <div><strong>Framework</strong> {summary.get("framework", "RBI FREE")}</div>
    <div><strong>Period</strong> {meta["period_start"]} → {meta["period_end"]}</div>
    <div><strong>Prepared by</strong> {meta["prepared_by"]}</div>
  </div>
</div>
<div class="score-banner">
  <div class="score-num" style="color:{score_color}">{score}%</div>
  <div class="score-label">
    <strong>RBI FREE Compliance Score (26 recommendations)</strong>
    {summary["compliant"]} compliant &nbsp;·&nbsp;
    {summary["partial"]} partial &nbsp;·&nbsp;
    {summary["non_compliant"]} gaps &nbsp;·&nbsp;
    {summary["not_assessed"]} not assessed
  </div>
</div>
<div class="section">
  <div class="section-title">Pillar Scores</div>
  <table>
  <tr><th>Pillar</th><th>Score</th><th>Bar</th></tr>
  {"".join(f'<tr><td>{p}</td><td><span class="pillar-score">{s}%</span></td><td><div style="background:#E5E7EB;border-radius:4px;height:12px;width:100%"><div style="background:#1D4ED8;border-radius:4px;height:12px;width:{s}%"></div></div></td></tr>' for p, s in summary["pillar_scores"].items())}
  </table>
</div>"""

    sections_html = ""
    for section in report_dict.get("sections", []):
        ps = section.get("score_pct", 0)
        pc = "#065F46" if ps >= 70 else "#92400E" if ps >= 45 else "#991B1B"
        sections_html += f"""
<div class="section">
  <div class="section-title">
    {section["title"]}
    <span style="float:right;font-size:20px;font-weight:800;color:{pc}">{ps}%</span>
  </div>
  {_checks_html(section.get("checks", []))}
</div>"""

    return _html_wrap(f"RBI FREE — {meta['organisation']}", cover + sections_html)
